# Generated by Django 3.1.1 on 2020-09-08 22:41

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20200908_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createpost',
            name='user',
        ),
        migrations.AlterField(
            model_name='createpost',
            name='post_img',
            field=models.ImageField(upload_to=gallery.models.prof_dir),
        ),
    ]
