# Generated by Django 3.1.1 on 2020-09-08 22:47

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20200908_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=gallery.models.prof_dir),
        ),
    ]
