# Generated by Django 3.1.1 on 2020-09-08 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20200908_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createpost',
            old_name='author',
            new_name='user',
        ),
    ]
