# Generated by Django 3.1.1 on 2020-09-08 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_auto_20200908_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createpost',
            name='user',
        ),
    ]
