# Generated by Django 3.1.1 on 2020-09-08 23:49

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_remove_createpost_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreatePost',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='post_img',
            field=models.ImageField(null=True, upload_to=gallery.models.prof_dir),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
