# Generated by Django 3.1.1 on 2020-09-09 00:20

from django.db import migrations, models
import django.db.models.deletion
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_auto_20200908_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='post_img',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='title',
        ),
        migrations.CreateModel(
            name='CreatePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_img', models.ImageField(upload_to=gallery.models.prof_dir)),
                ('title', models.CharField(max_length=50)),
                ('userProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.userprofile')),
            ],
        ),
    ]
