# Generated by Django 3.1.1 on 2020-09-09 08:16

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_auto_20200909_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpost',
            name='post_img',
            field=models.FileField(upload_to=gallery.models.prof_dir),
        ),
    ]
