# Generated by Django 3.1.1 on 2020-09-09 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_auto_20200909_0816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createpost',
            old_name='userProfile',
            new_name='userprofile',
        ),
    ]
