# Generated by Django 3.1.1 on 2020-09-09 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_auto_20200909_0839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createpost',
            old_name='userprofile',
            new_name='user',
        ),
    ]
