# Generated by Django 3.1.1 on 2020-09-10 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0016_auto_20200909_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='post',
            field=models.ManyToManyField(to='gallery.Post'),
        ),
    ]
