# Generated by Django 3.1.1 on 2020-09-11 23:59

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0017_userprofile_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/camera.jpg', upload_to=gallery.models.prof_dir),
        ),
    ]
